version: '3.9'


services:
    server:
        restart: unless-stopped
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        entrypoint: /app/docker/server-entrypoint.sh
        expose:
            - 80
        ports:
            - 80:8000
        environment:
            - HOST_INFO
